# Muralizer database config

development:
  adapter: postgresql
  database: muralizer_development
  username: muralizer
  password: "M394P455W0Rd!!!"
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

test: &TEST
  adapter: postgresql
  database: muralizer_test
  username: muralizer
  password: "M394P455W0Rd!!!"
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

cucumber:
 <<: *TEST

production:
  adapter: postgresql
  database: muralizer_production
  username: muralizer
  password: "M394P455W0Rd!!!"
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000
